name: "Release"

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"  # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: Build
        uses: goreleaser/goreleaser-action@v4
        if: ${{ github.event_name == 'pull_request' }}
        with:
          version: latest
          args: build --skip-validate   # skip validate skips initial sanity checks in order to be able to fully run

      - run: |
          VERSION=${GITHUB_REF#refs/tags/}
          HEADING=${VERSION//./}
          echo https://github.com/informalsystems/ghere/blob/${VERSION}/CHANGELOG.md#${HEADING} > ../release_notes.md

      - name: Release
        uses: goreleaser/goreleaser-action@v4
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --rm-dist --release-notes=../release_notes.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
